name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_backend:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Backend folder
      uses: actions/checkout@v3
      with:
        path: server
    - name: Use Node.js 20.3.1
      uses: actions/setup-node@v2
      with:
         node-version: 16.14.0
         cache: "npm"
    - name: Install Dependencies
      working-directory: ./server
      run: npm i
    - name: Run Tests
      working-directory: ./server
      run: npm test

  build_frontend:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Frontend folder
      uses: actions/checkout@v3
      with:
        path: my-app
    - name: Use Node.js 20.3.1
      uses: actions/setup-node@v3
      with:
        node-version: 20.3.1
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install Dependencies
      working-directory: ./my-app
      run: npm i
    - name: Build Project
      working-directory: ./my-app
      run: npm run build --if-present

# Stop the workflow if the "test_folder_1" job fails
  fail-on-test-failure:
    needs: test_backend
    if: ${{ needs.test_backend.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
    - name: Fail the workflow
      run: exit 1
