name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test_backend:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Backend folder
      uses: actions/checkout@v3
      with:
        path: DevOpsBackend
    - name: Use Node.js 20.3.1
      uses: actions/setup-node@v2
      with:
         node-version: 20.3.1
         cache: "npm"
         cache-dependency-path: DevOpsBackend/server/package-lock.json
    - name: Install Dependencies
      working-directory: ./DevOpsBackend/server
      run: npm i
    - name: Run Tests
      working-directory: ./DevOpsBackend/server
      run: npm test

  build_frontend:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Frontend folder
      uses: actions/checkout@v3
      with:
        path: DevOpsFrontend
    - name: Use Node.js 20.3.1
      uses: actions/setup-node@v3
      with:
        node-version: 20.3.1
        cache: 'npm'
        cache-dependency-path: DevOpsFrontend/my-app/package-lock.json
    - name: Install Dependencies
      working-directory: ./DevOpsFrontend/my-app
      run: npm i
    - name: Build Project
      working-directory: ./DevOpsFrontend/my-app
      run: npm run build --if-present

  send_discord_notification:
    runs-on: ubuntu-latest
    needs: [test_backend, build_frontend]
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: 'https://discord.com/api/webhooks/1125824673112916149/r3nfgEovUo4HHhjiRLvCaYFn7te-U8fpkREFz-XOFvzURPVBE_U-yWVcKQqBqZCfOLBn'
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
