name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test_backend:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Backend folder
      uses: actions/checkout@v3
      with:
        path: DevOpsBackend
    - name: Use Node.js 20.3.1
      uses: actions/setup-node@v2
      with:
         node-version: 20.3.1
         cache: "npm"
         cache-dependency-path: DevOpsBackend/server/package-lock.json
    - name: Install Dependencies
      working-directory: ./DevOpsBackend/server
      run: npm i
    - name: Run Tests
      working-directory: ./DevOpsBackend/server
      run: npm test

  build_frontend:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Backend folder
      uses: actions/checkout@v3
      with:
        path: DevOpsFrontend
    - name: Use Node.js 20.3.1
      uses: actions/setup-node@v3
      with:
        node-version: 20.3.1
        cache: 'npm'
        cache-dependency-path: DevOpsFrontend/my-app/package-lock.json
    - name: Install Dependencies
      working-directory: ./DevOpsFrontend/my-app
      run: npm i
    - name: Build Project
      working-directory: ./DevOpsFrontend/my-app
      run: npm run build --if-present
    - name: lsing
      run: ls
    - name: lsing
      run: ls DevOpsFrontend/my-app/
    - name: Cache build directory
      uses: actions/cache@v3
      with:
        path: ./DevOpsFrontend/my-app/build
        key: ${{ runner.os }}-frontend-${{ hashFiles('**/package-lock.json') }}
